Repository cloud-pi-native/console, pull requests merged in 2023-05, with the labels that each got.

#374 chore: :arrow_up: upgrade all minor / patch dependancies
  apps/client/package.json
  apps/client/src/components/CIForm.vue
  apps/server/package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: dette technique

#373 feat: :lipstick: better ui for permission form
  apps/client/src/components/PermissionForm.vue
  apps/client/src/components/RangeInput.vue
  apps/client/src/views/projects/ManageEnvironments.vue
Labels: enhancement, dette technique

#404 refactor: :recycle: use class selector instead of html tag
  apps/client/src/components/RangeInput.vue
Labels: dette technique

#403 build: :technologist: display app version in frontend
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  apps/client/Dockerfile
  apps/client/src/App.vue
  apps/client/src/main.css
  apps/server/Dockerfile
  apps/server/src/app.spec.js
  apps/server/src/routes/index.js
  docker/docker-compose.prod.yml
Labels: tech

#407 chore: :memo: fix changelog
  CHANGELOG.md
Labels: dette technique

#412 fix: :ambulance: keycloak now sends group path
  apps/client/cypress/components/specs/range.input.ct.js
  apps/client/cypress/components/specs/repo-form.ct.js
  apps/client/src/components/EnvironmentForm.vue
  apps/client/src/components/PermissionForm.vue
  apps/client/src/stores/user.js
  apps/client/src/stores/user.spec.js
  apps/client/src/views/projects/ManageEnvironments.vue
  apps/server/src/controllers/admin/organizations.js
  apps/server/src/controllers/admin/project.js
  apps/server/src/controllers/admin/user.js
  apps/server/src/routes/admin/organization.spec.js
  apps/server/src/routes/admin/user.spec.js
  apps/server/src/routes/organization.spec.js
  keycloak/realms/realm-dev.json
  packages/shared/src/schemas/environment.js
  packages/shared/src/schemas/project.js
  packages/shared/src/schemas/repository.js
  packages/shared/src/utils/const.js
  packages/shared/src/utils/functions.js
  packages/test-utils/src/random-project.js
  packages/test-utils/src/random-utils.js
Labels: bug

#421 refactor: :recycle: improve code structure
  .github/workflows/release.yml
  README.md
  apps/client/src/components/CIForm.vue
  apps/client/src/documentation/doc.md
  apps/client/src/documentation/home.md
  apps/server/src/generate-files/templates/docker.yml
  apps/server/src/generate-files/templates/gitlab-ci.yml
  apps/server/src/generate-files/templates/vault.yml
  apps/server/src/plugins/core/gitlab/files/.gitlab-ci.yml
  apps/server/src/plugins/core/gitlab/files/mirror.sh
  apps/server/src/plugins/core/gitlab/group.js
  apps/server/src/plugins/core/kubernetes/utils.js
  apps/server/src/plugins/core/vault/index.js
  apps/server/src/plugins/core/vault/init.js
  apps/server/vitest-init.js
  misc/architecture.drawio
  misc/business-rules.md
  misc/controllers.md
  misc/plugins.md
Labels: dette technique

#422 build: :construction_worker: change client base image to bitnami/nginx
  apps/client/Dockerfile
  apps/client/nginx/default.conf
  apps/client/nginx/default.conf.tpl
  apps/client/nginx/entrypoint.sh
  apps/client/nginx/nginx.conf
Labels: docker, tech

#428 refactor: :loud_sound: harmonize api logs
  apps/server/package.json
  apps/server/src/connect.js
  apps/server/src/controllers/admin/organizations.js
  apps/server/src/controllers/admin/project.js
  apps/server/src/controllers/admin/user.js
  apps/server/src/controllers/environment.js
  apps/server/src/controllers/organization.js
  apps/server/src/controllers/permission.js
  apps/server/src/controllers/project.js
  apps/server/src/controllers/repository.js
  apps/server/src/controllers/service.js
  apps/server/src/controllers/user.js
  apps/server/src/generate-files/generate-ci-files.js
  apps/server/src/routes/admin/organization.spec.js
  apps/server/src/routes/admin/user.spec.js
  apps/server/src/routes/organization.spec.js
  apps/server/src/routes/project-environment.spec.js
  apps/server/src/routes/project-permission.spec.js
  apps/server/src/routes/project-repository.spec.js
  apps/server/src/routes/project-user.spec.js
  apps/server/src/routes/project.spec.js
  apps/server/src/utils/logger.js
  pnpm-lock.yaml
Labels: dette technique, tech
