Repository cloud-pi-native/console, pull requests merged in 2023-07, with the labels that each got.

#499 :children_crossing: Ajout de l'organisation pour différencier le projet
  apps/client/cypress/e2e/specs/projects.e2e.js
  apps/client/cypress/e2e/specs/redirection.e2e.js
  apps/client/src/stores/project.js
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoSelectedProject.vue
Labels: enhancement

#501 chore: :arrow_up: upgrade dependencies
  apps/client/.eslintrc.cjs
  apps/client/Dockerfile
  apps/client/cypress/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  apps/server/src/prisma/schema.prisma
  docker/docker-compose.ci.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.int.yml
  docker/docker-compose.prod.yml
  helm/templates/deployment-postgres.yml
  package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: dette technique, tech

#506 fix: :bug: missing await before plugins hook and logs recording on archiveProject
  apps/server/src/controllers/project.ts
Labels: bug

#514 chore: :arrow_up: upgrade dependencies
  apps/client/package.json
  apps/server/package.json
  apps/server/src/plugins/core/gitlab/user.ts
  package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: bug, tech

#515 feat: :alien: add updateProject hook (for description / archive update)
  apps/server/src/controllers/project.ts
  apps/server/src/plugins/hooks/project.ts
Labels: enhancement

#522 fix: :bug: delete kube resources when deleting a project
  apps/server/src/controllers/project.ts
  apps/server/src/plugins/core/argo/app-project.ts
  apps/server/src/plugins/core/argo/index.ts
  apps/server/src/plugins/core/argo/migrate.ts
  apps/server/src/plugins/core/gitlab/project.ts
  apps/server/src/queries/cluster-queries.ts
Labels: bug

#524 feat: :children_crossing: improve gitlab mirroring by using a single …
  apps/client/src/components/CIForm.vue
  apps/server/src/generate-files/templates/gitlab-ci.yml
  apps/server/src/plugins/core/argo/index.ts
  apps/server/src/plugins/core/gitlab/files/.gitlab-ci.yml
  apps/server/src/plugins/core/gitlab/files/mirror.sh
  apps/server/src/plugins/core/gitlab/index.ts
  packages/test-utils/src/imports/data.js
Labels: enhancement
