Repository cloud-pi-native/console, pull requests merged in 2023-10, with the labels that each got.

#713 chore: :arrow_up: upgrade root dependencies
  .github/workflows/ci.yml
  apps/client/Dockerfile
  apps/client/cypress/e2e/specs/admin/organizations.e2e.ts
  apps/server/Dockerfile
  apps/server/package.json
  ci/act/workflows/ci.yml
  package.json
  packages/eslintconfig/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: tech

#716 feat: :sparkles: enable admin cluster update
  apps/client/cypress/components/specs/cluster-form.ct.ts
  apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
  apps/client/src/components/ClusterForm.vue
Labels: enhancement

#725 test: :label: add types for cypress
  apps/client/cypress/components/support/commands.ts
  apps/client/cypress/components/support/index.ts
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/support/func.ts
  apps/client/cypress/e2e/support/index.ts
  apps/client/cypress/tsconfig.json
  apps/client/cypress/types.ts
Labels: dette technique, tech

#729 Tech/improve build time
  .dockerignore
  .github/workflows/build.yml
  .github/workflows/cache.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/scan.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-deploy.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .lintstagedrc
  apps/client/Dockerfile
  apps/server/Dockerfile
  ci/act/workflows/lint.yml
  ci/act/workflows/tests-component.yml
  ci/act/workflows/tests-deploy.yml
  ci/act/workflows/tests-e2e.yml
  ci/act/workflows/tests-unit.yml
  ci/kind/run.sh
  ci/scripts/build-tags.sh
  ci/scripts/delete-image.sh
  ci/scripts/run-tests.sh
Labels: tech

#732 ci: :green_heart: bug fixed after runtime improvement
  .github/workflows/build.yml
  .github/workflows/cache.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: bug

#744 fix: :ambulance: send internalRepoName to plugins on updateRepository hook
  apps/client/src/views/projects/DsoRepos.vue
  apps/server/src/prisma/migrations/20231010111515_dso/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/repository/controllers.ts
  apps/server/src/resources/repository/queries.ts
  packages/test-utils/src/imports/data.ts
Labels: bug

#765 ci: :green_heart: fix ci build workflow
  .github/workflows/build.yml
  .github/workflows/cache.yml
  .github/workflows/cd.yml
Labels: bug, CI/CD

#770 feat: :children_crossing: add default branch to sync in mirror pipeline
  .github/workflows/tests-unit.yml
  .gitlab-ci-dso.yml
  apps/server/src/plugins/core/gitlab/files/.gitlab-ci.yml
Labels: enhancement

#772 Docs/improve repository ux
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  apps/client/package.json
  apps/server/package.json
  ci/scripts/run-tests.sh
  package.json
  packages/shared/package.json
  packages/test-utils/package.json
  turbo.json
Labels: documentation

#779 Refactor/improve dev and user experience
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-deploy.yml
  .github/workflows/tests-e2e.yml
  README.md
  ci/kind/run.sh
  ci/scripts/run-tests.sh
  env/.env.int-example
Labels: enhancement, tech

#799 ci: :construction_worker: enable multi browsers tests through cypress
  .github/workflows/cache.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-deploy.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  apps/client/cypress.config.ts
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/client/package.json
  ci/scripts/run-tests.sh
  package.json
Labels: CI/CD

#801 Tech/upgrade dependencies
  .github/workflows/ci.yml
  apps/client/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  ci/act/workflows/ci.yml
  package.json
  packages/eslintconfig/package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: tech
