Repository cloud-pi-native/console, pull requests merged in 2023-03, with the labels that each got.

#257 refactor: :recycle: divide project store
  apps/client/src/components/PermissionForm.vue
  apps/client/src/stores/project-environment.js
  apps/client/src/stores/project-permission.js
  apps/client/src/stores/project-repository.js
  apps/client/src/stores/project-user.js
  apps/client/src/stores/project.js
  apps/client/src/views/projects/DsoRepos.vue
  apps/client/src/views/projects/DsoTeam.vue
  apps/client/src/views/projects/ManageEnvironments.vue
Labels: dette technique, tech

#264 fix: :bug: do nothing when tile is disabled
  apps/client/cypress/e2e/support/commands.js
  apps/client/src/components/RepoForm.vue
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRepos.vue
Labels: bug

#293 Feat/generate url services on backend
  README.md
  ansible/playbooks/import_all.yml
  apps/ansible-api/Dockerfile
  apps/ansible-api/env/.env-example
  apps/ansible-api/env/.env.ci-example
  apps/ansible-api/package.json
  apps/ansible-api/src/server.js
  apps/ansible-api/src/utils/env.js
  apps/client/Dockerfile
  apps/client/cypress/Dockerfile
  apps/client/cypress/e2e/specs/create-project.e2e.js
  apps/client/cypress/e2e/specs/repos.e2e.js
  apps/client/cypress/e2e/support/commands.js
  apps/client/env/.env-example
  apps/client/env/.env.ci-example
  apps/client/index.html
  apps/client/nginx/entrypoint.sh
  apps/client/package.json
  apps/client/src/api/api.js
  apps/client/src/api/api.spec.js
  apps/client/src/utils/env.js
  apps/client/src/views/projects/DsoServices.vue
  apps/client/vite.config.js
  apps/server/Dockerfile
  apps/server/env/.env-example
  apps/server/env/.env.ci-example
  apps/server/package.json
  apps/server/src/connect.spec.js
  apps/server/src/controllers/permission.js
  apps/server/src/controllers/project.js
  apps/server/src/models/queries/project-queries.js
  apps/server/src/routes/organization.spec.js
  apps/server/src/routes/project-permission.spec.js
  apps/server/src/server.js
  apps/server/src/utils/env.js
  apps/server/src/utils/keycloak.spec.js
  apps/server/src/utils/matches.js
  apps/server/src/utils/queries-tools.js
  apps/server/src/utils/queries-tools.spec.js
  apps/server/src/utils/services.js
  apps/server/src/utils/services.spec.js
  ci/scripts/run-tests.sh
  db/postgres/scripts/010-init-db.sql
  docker/docker-compose.ci.yml
  docker/docker-compose.ct.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.prod.yml
  env/.env-example
  env/.env.ci-example
  package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: enhancement, dette technique

#304 Refacto/sonar review before release
  apps/server/src/models/queries/log-queries.js
Labels: dette technique

#315 refactor: :coffin: isAdmin key is no longer used
  apps/server/src/models/queries/user-queries.js
  apps/server/src/models/user.js
  apps/server/src/utils/env.js
Labels: dette technique

#320 style: :lipstick: improve markdown css
  apps/client/src/markdown.css
  apps/client/vite.config.js
Labels: enhancement

#321 Test/add store tests
  apps/client/src/api/api.js
  apps/client/src/api/api.spec.js
  apps/client/src/components/CIForm.vue
  apps/client/src/stores/ci-files.js
  apps/client/src/stores/ci-files.spec.js
  apps/client/src/stores/organization.spec.js
  apps/client/src/stores/project-environment.spec.js
  apps/client/src/stores/project-permission.spec.js
  apps/client/src/stores/project-repository.spec.js
  apps/client/src/stores/project-user.spec.js
  apps/client/src/stores/project.spec.js
  apps/client/src/stores/services.js
  apps/client/src/stores/services.spec.js
  apps/client/src/stores/snackbar.js
  apps/client/src/stores/snackbar.spec.js
  apps/client/src/stores/user.spec.js
  apps/client/src/views/ServicesHealth.vue
  apps/server/src/routes/service.spec.js
Labels: dette technique
