Repository cloud-pi-native/console, pull requests merged in 2023-11, with the labels that each got.

#812 fix: :bug: fix endless redirect on login if authenticated
  apps/client/cypress/e2e/specs/redirection.e2e.ts
  apps/client/src/router/index.ts
Labels: bug

#822 ci: :construction_worker: fix branch name on manually triggered sonar scan
  .github/workflows/tests-unit.yml
Labels: bug, CI/CD

#827 ci: :construction_worker: remove test files duplication count in sonar
  .github/workflows/lint.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
Labels: CI/CD

#850 chore: :arrow_up: upgrade nodejs to v20.10.0
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  apps/client/Dockerfile
  apps/server/Dockerfile
  ci/act/workflows/ci.yml
  package.json
Labels: tech
