Repository cloud-pi-native/console, pull requests merged in 2023-02, with the labels that each got.

#157 feat: :lipstick: fix snackbar on bottom left
  apps/client/src/App.vue
Labels: enhancement

#163 Feat/add crypto module
  apps/ansible-api/package.json
  apps/ansible-api/vitest-init.js
  apps/ansible-api/vitest.config.js
  apps/server/src/controllers/repository.js
  apps/server/src/utils/crypto.js
  apps/server/src/utils/crypto.spec.js
  apps/server/src/utils/env.js
  apps/server/vitest-init.js
  apps/server/vitest.config.js
  docker/docker-compose.ci.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.prod.yml
  env/.env-example
  env/.env.ci-example
Labels: tech, security

#164 fix: :lock: improve security using node utility function to compare hashes
  apps/server/src/utils/crypto.js
Labels: tech, security

#166 feat: :sparkles: add backend function to generate random passwords
  apps/server/src/utils/crypto.js
  apps/server/src/utils/crypto.spec.js
Labels: tech, security

#161 refactor(Helm): :wrench: remove matches.js
  apps/ansible-api/src/utils/env.js
  apps/server/src/utils/env.js
  docker/docker-compose.ci.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.prod.yml
  env/.env-example
  env/.env.ci-example
  helm/templates/ansible-matches-configmap.yml
  helm/templates/cm-ansible.yml
  helm/templates/deployment-ansible.yml
  helm/templates/matches-configmap.yml
  helm/values.yaml
Labels: tech

#167 ci: :construction_worker: improve ci
  .github/workflows/cache.yml
  .github/workflows/release.yml
  apps/client/cypress/Dockerfile
  ci/act/docker/registry/docker-compose.registry.yml
  ci/act/env/.env-example
  ci/act/events/pr_base_main.json
  ci/act/events/pr_draft.json
  ci/act/events/pr_not_draft.json
  ci/act/events/push_base_main.json
  ci/act/events/push_tag.json
  ci/act/scripts/run-ci-locally.sh
  ci/act/workflows/scan/scan.yml
  ci/act/workflows/test.yml
  ci/act/workflows/test/test.yml
  ci/scripts/build-matrix.sh
  ci/scripts/run-tests.sh
  docker/docker-compose.ci.yml
  docker/docker-compose.ct.yml
  docker/docker-compose.dev.yml
Labels: docker, CI/CD

#173 ci: :construction_worker: build and release workflows separation
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: CI/CD

#174 fix: :card_file_box: organization should be a FK in projects
  apps/server/src/models/organization.js
Labels: dette technique

#182 Ci/improve ci build system
  .github/workflows/build.yml
  .github/workflows/release.yml
  ci/scripts/build-matrix.sh
Labels: CI/CD

#184 ci: :construction_worker: remove arm64 build for branch build
  .github/workflows/build.yml
  ci/scripts/build-matrix.sh
Labels: CI/CD

#201 fix: :bug: send200 if status is OK
  apps/ansible-api/src/controllers/generic.js
  apps/server/src/controllers/project.js
  apps/server/src/controllers/repository.js
Labels: bug

#204 fix: :bug: controller response before ansible fetch
  apps/client/cypress/e2e/support/commands.js
  apps/client/src/main.css
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/server/src/controllers/repository.js
  apps/server/src/routes/project-repository.spec.js
Labels: bug

#207 fix: :bug: update ansible calls
  apps/client/src/App.vue
  apps/client/src/components/RepoForm.vue
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/server/src/controllers/project.js
  apps/server/src/controllers/repository.js
Labels: bug

#214 Fix/handle server errors
  apps/client/src/App.vue
  apps/client/src/api/xhr-client.js
  apps/client/src/api/xhr-client.spec.js
  apps/client/src/components/PermissionForm.vue
  apps/client/src/router/index.js
  apps/client/src/views/CreateProject.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/client/src/views/projects/DsoTeam.vue
  apps/client/src/views/projects/ManageEnvironments.vue
Labels: bug

#213 docs: :memo: update user documentation
  apps/client/cypress/components/specs/repo-form.ct.js
  apps/client/cypress/e2e/support/commands.js
  apps/client/src/documentation/doc.md
  apps/server/src/generate-files/generate-ci-files.js
Labels: documentation

#218 fix: :goal_net: catch fetch errors and send it to front
  apps/server/src/controllers/project.js
  apps/server/src/controllers/repository.js
  apps/server/src/routes/project.spec.js
Labels: bug

#220 ci: :green_heart: fix ci build on release
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: CI/CD

#221 feat: :lipstick: whoami in sidemenu rather than snackbar
  apps/client/cypress/e2e/specs/home.e2e.js
  apps/client/src/App.vue
  apps/client/src/components/SideMenu.vue
Labels: enhancement

#222 fix: :goal_net: optional chaining to avoid errors on selected project
  apps/client/cypress/components/specs/permission-form.ct.js
  apps/client/cypress/e2e/specs/repos.e2e.js
  apps/client/src/components/CIForm.vue
  apps/client/src/components/SideMenu.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/client/src/views/projects/DsoTeam.vue
  apps/client/src/views/projects/ManageEnvironments.vue
Labels: bug

#223 ci: :green_heart: try to build rootless image for postgress 14.5
  apps/ansible-api/src/ansible.js
  db/Dockerfile
  docker/docker-compose.ci.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.prod.yml
  helm/templates/deployment-postgres.yml
Labels: docker

#228 fix: :lipstick: enforce ui on disabled dsfrtiles
  apps/client/src/main.css
Labels: bug

#227 fix: :bug: create user and env at project creation
  apps/server/src/controllers/environment.js
  apps/server/src/controllers/project.js
  apps/server/src/models/queries/project-queries.js
  apps/server/src/routes/project.spec.js
Labels: bug

#233 ci: :construction_worker: improve ci
  .github/workflows/test.yml
  apps/ansible-api/Dockerfile
  apps/client/Dockerfile
  apps/client/cypress/Dockerfile
  apps/server/Dockerfile
  ci/act/docker/Dockerfile
  db/Dockerfile
  docker/docker-compose.ci.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.e2e.yml
  docker/docker-compose.prod.yml
Labels: docker

#234 feat: :children_crossing: redirect to services when selecting a project
  apps/client/cypress/e2e/specs/projects.e2e.js
  apps/client/cypress/e2e/specs/redirection.e2e.js
  apps/client/cypress/e2e/specs/sidebar.e2e.js
  apps/client/src/views/projects/DsoProjects.vue
Labels: enhancement

#258 template gitlab-ci
  apps/client/src/components/CIForm.vue
  apps/server/src/generate-files/generate-ci-files.spec.js
  apps/server/src/generate-files/templates/gitlab-ci.yml
  apps/server/src/generate-files/templates/vault.yml
Labels: enhancement

#259 fix: :bug: add joi schema validation in repo form
  apps/client/cypress/e2e/specs/repos.e2e.js
  apps/client/src/components/RepoForm.vue
  packages/shared/src/schemas/repository.js
Labels: bug

#241 feat: :sparkles: display project and repositories statuses
  apps/client/cypress/e2e/specs/create-project.e2e.js
  apps/client/cypress/e2e/specs/dashboard.e2e.js
  apps/client/cypress/e2e/specs/repos.e2e.js
  apps/client/cypress/e2e/support/commands.js
  apps/client/src/App.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoRepos.vue
  packages/test-utils/src/imports/data.js
Labels: enhancement
