Repository cloud-pi-native/console, pull requests merged in 2023-04, with the labels that each got.

#327 fix: :bug: display hyphen only if service message exists
  apps/client/src/components/DsoSnackbar.vue
  apps/client/src/views/ServicesHealth.vue
Labels: enhancement

#348 ci: :bug: handle exit code on tests run in ci
  ci/scripts/run-tests.sh
  package.json
Labels: CI/CD

#349 ci: :construction_worker: bump action version & add latest tag to images
  .github/workflows/release.yml
Labels: docker, CI/CD

#352 fix: :bug: fix git output url
  apps/server/src/plugins/core/gitlab/index.js
Labels: bug

#354 ci: :pushpin: update images tags in helm values
  helm/values.yaml
Labels: docker, CI/CD

#303 Feat/administration
  README.md
  apps/client/cypress/e2e/specs/admin-users.e2e.js
  apps/client/cypress/e2e/specs/sidebar.e2e.js
  apps/client/cypress/e2e/support/commands.js
  apps/client/cypress/e2e/support/func.js
  apps/client/src/api/api.js
  apps/client/src/api/api.spec.js
  apps/client/src/components/SideMenu.vue
  apps/client/src/router/index.js
  apps/client/src/stores/admin/user.js
  apps/client/src/stores/user.js
  apps/client/src/stores/user.spec.js
  apps/client/src/utils/date.js
  apps/client/src/utils/keycloak/keycloak.js
  apps/client/src/views/admin/ListUser.vue
  apps/server/src/controllers/admin/project.js
  apps/server/src/controllers/admin/user.js
  apps/server/src/controllers/project.js
  apps/server/src/models/queries/project-queries.js
  apps/server/src/routes/admin/user.js
  apps/server/src/routes/admin/user.spec.js
  apps/server/src/routes/index.js
  apps/server/src/routes/project-user.js
  keycloak/realms/realm-dev.json
Labels: enhancement
