Repository cloud-pi-native/console, pull requests merged in 2024-08, with the labels that each got.

#1304 fix: :ambulance: handle missing commit in gitlab repo
  plugins/gitlab/src/class.ts
  pnpm-lock.yaml
Labels: bug, built

#1312 fix: :ambulance: handle missing commit in gitlab repo
  plugins/gitlab/src/class.ts
  pnpm-lock.yaml
Labels: bug, built

#1317 ci: :construction_worker: upgrade github actions
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/release.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  ci/act/workflows/lint.yml
  ci/act/workflows/tests-component.yml
  ci/act/workflows/tests-deploy.yml
  ci/act/workflows/tests-e2e.yml
  ci/act/workflows/tests-unit.yml
Labels: CI/CD, built

#1294 feat: :sparkles: maintenance mode
  apps/client/cypress/e2e/specs/admin/system-settings.e2e.ts
  apps/client/src/App.vue
  apps/client/src/api/xhr-client.ts
  apps/client/src/components/SideMenu.vue
  apps/client/src/icons.ts
  apps/client/src/router/index.ts
  apps/client/src/stores/system-settings.spec.ts
  apps/client/src/stores/system-settings.ts
  apps/client/src/views/DsoMaintenance.vue
  apps/client/src/views/admin/SystemSettings.vue
  apps/server/src/prisma/migrations/20240808082632_dso/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/index.ts
  apps/server/src/resources/queries-index.ts
  apps/server/src/resources/system/settings/business.ts
  apps/server/src/resources/system/settings/controllers.spec.ts
  apps/server/src/resources/system/settings/queries.ts
  apps/server/src/resources/system/settings/router.ts
  apps/server/src/utils/controller.ts
  apps/server/src/utils/errors.ts
  packages/shared/src/api-client.ts
  packages/shared/src/contracts/system.ts
  packages/shared/src/schemas/system.ts
  packages/shared/src/utils/functions.ts
  packages/shared/src/utils/types.ts
  packages/test-utils/src/imports/data.ts
  pnpm-lock.yaml
Labels: preview, built

#1301 refactor: :recycle: group admin routes
  apps/client/src/router/index.ts
Labels: refactor, built

#1298 feat: :sparkles: add project dedicated approle and policy in vault
  plugins/argocd/package.json
  plugins/argocd/src/env.d.ts
  plugins/argocd/src/functions.ts
  plugins/vault/src/class.ts
  plugins/vault/src/functions.ts
  plugins/vault/src/index.ts
  pnpm-lock.yaml
Labels: built

#1320 ci: :construction_worker: check for package version update and publish
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/npm.yml
Labels: CI/CD, built

#1321 feat: :sparkles: option to mirror all branches
  apps/client/cypress/e2e/specs/repos.e2e.ts
  apps/client/src/stores/project-repository.ts
  apps/client/src/views/projects/DsoRepos.vue
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/repository/controllers.spec.ts
  apps/server/src/resources/repository/router.ts
  apps/server/src/utils/hook-wrapper.ts
  packages/hooks/package.json
  packages/hooks/src/hooks/hook-misc.ts
  packages/shared/package.json
  packages/shared/src/schemas/repository.ts
  plugins/gitlab/files/.gitlab-ci.yml
  plugins/gitlab/package.json
  plugins/gitlab/src/class.ts
  plugins/gitlab/src/functions.ts
Labels: enhancement, built

#1323 Chore/upgrade nodejs
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .prototools
  README.md
  apps/client/Dockerfile
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/server/.env.integ-example
  apps/server/Dockerfile
  ci/helm-utils/templates/deployment-pgadmin.yaml
  ci/kind/env/dso-values-integ-example.yaml
  ci/kind/run.sh
  docker/docker-compose.dev.yml
  docker/docker-compose.integ.yml
  docker/docker-compose.local.yml
  env/.env.integ-example
  package.json
  pgadmin/servers-docker.json
  pgadmin/servers-kube.json
Labels: tech, built

#1326 refactor: :recycle: parent admin check
  apps/client/src/App.vue
  apps/client/src/router/index.ts
  apps/client/src/stores/user.spec.ts
  apps/client/src/stores/user.ts
  apps/client/src/views/admin/DsoAdmin.vue
Labels: built

#1325 Fix/system-setting-e2e
  apps/client/cypress/e2e/specs/admin/system-settings.e2e.ts
Labels: built

#1327 test: :test_tube: add roles test
  apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/specs/admin/roles.e2e.ts
  apps/client/src/components/AdminRoleForm.vue
  apps/client/src/components/ChoiceSelector.vue
  apps/client/src/components/ConfigParam.vue
  apps/client/src/components/ProjectRoleForm.vue
  apps/client/src/components/SuggestionInput.vue
  apps/client/src/components/TeamCt.vue
  apps/client/src/views/admin/AdminRoles.vue
  apps/client/src/views/admin/ListPlugins.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoRoles.vue
Labels: preview, built

#1324 Refactor/admin org placeholder
  apps/client/src/views/admin/ListOrganizations.vue
Labels: built

#1331 Hotfix/minor-fixes
  apps/client/src/components/ProjectRoleForm.vue
  apps/server/src/resources/project-member/router.ts
Labels: built

#1338 Fix/edit-migration
  apps/server/src/prisma/migrations/20240723135420_dso/migration.sql
Labels: built

#1339 perf: :zap: avoid unuseful keycloak call and auto-refresh
  apps/client/src/api/xhr-client.ts
  apps/client/src/main.ts
  apps/client/src/utils/keycloak/keycloak.ts
  keycloak/realms/realm-dev.json
Labels: built

#1346 chore: :hammer: bump packages versions
  packages/eslintconfig/package.json
  packages/hooks/package.json
  packages/shared/package.json
  plugins/argocd/package.json
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
Labels: built
