Repository cloud-pi-native/console, pull requests merged in 2024-11, with the labels that each got.

#1431 feat: :lipstick: disable cluster selection when creating a zone
  apps/client/cypress/components/specs/zone-form.ct.ts
  apps/client/cypress/e2e/specs/admin/zones.e2e.ts
  apps/client/src/components/ZoneForm.vue
Labels: preview, built

#1436 fix: :bug: minors plugins fix and front
  apps/client/src/components/RepoForm.vue
  apps/client/src/views/projects/DsoProjectWrapper.vue
  apps/server/src/resources/project/business.spec.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/system/router.ts
  apps/server/src/utils/env.ts
  apps/server/src/utils/fastify.ts
  apps/server/src/utils/hook-wrapper.ts
  packages/shared/package.json
  packages/shared/src/utils/functions.spec.ts
  packages/shared/src/utils/functions.ts
  plugins/argocd/package.json
  plugins/argocd/src/app-project.ts
  plugins/argocd/src/applications.ts
  plugins/argocd/src/functions.ts
  plugins/argocd/src/index.ts
  plugins/argocd/src/utils.ts
  plugins/gitlab/package.json
  plugins/gitlab/src/class.ts
  plugins/harbor/package.json
  plugins/harbor/src/robot.ts
  plugins/kubernetes/package.json
  plugins/kubernetes/src/class.ts
  plugins/kubernetes/src/misc.ts
  plugins/nexus/package.json
  plugins/nexus/src/project.ts
  plugins/vault/package.json
  plugins/vault/src/class.ts
Labels: preview, built

#1437 feat: :lipstick: user list rework
  .vscode/settings.json
  apps/client/cypress/e2e/specs/admin/roles.e2e.ts
  apps/client/cypress/e2e/specs/admin/users.e2e.ts
  apps/client/cypress/e2e/support/commands.ts
  apps/client/src/utils/project-utils.ts
  apps/client/src/views/admin/ListUser.vue
  apps/server/package.json
  apps/server/src/prisma/migrations/20241104232540_add_usertype/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/prisma/schema/admin.prisma
  apps/server/src/prisma/schema/project.prisma
  apps/server/src/prisma/schema/schema.prisma
  apps/server/src/prisma/schema/token.prisma
  apps/server/src/prisma/schema/topography.prisma
  apps/server/src/prisma/schema/user.prisma
  apps/server/src/resources/project/router.spec.ts
  apps/server/src/resources/user/business.spec.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/queries.ts
  apps/server/src/resources/user/router.spec.ts
  apps/server/src/types/index.ts
  apps/server/src/utils/mocks.ts
  packages/shared/package.json
  packages/shared/src/schemas/token.ts
  packages/shared/src/schemas/user.ts
  packages/shared/src/utils/schemas.spec.ts
  packages/test-utils/src/imports/data.ts
Labels: preview, built

#1440 feat: :sparkles: nexus customizable write policy
  plugins/nexus/package.json
  plugins/nexus/src/infos.ts
  plugins/nexus/src/maven.ts
  plugins/nexus/src/npm.ts
  plugins/nexus/src/project.ts
  plugins/nexus/src/utils.ts
Labels: built

#1442 Feat/nexus and hooks improvement
  apps/client/src/components/ServicesConfig.vue
  apps/server/src/resources/project-service/business.ts
  apps/server/src/resources/project-service/queries.ts
  packages/hooks/package.json
  packages/hooks/src/hooks/hook.ts
  packages/shared/package.json
  packages/shared/src/schemas/config.ts
  plugins/nexus/package.json
  plugins/nexus/src/infos.ts
  plugins/nexus/src/maven.ts
  plugins/nexus/src/project.ts
  plugins/nexus/src/utils.ts
Labels: preview, built

#1443 Develop
  apps/client/src/components/ServicesConfig.vue
  apps/client/src/views/admin/ListUser.vue
  apps/server/src/prisma/migrations/20241107142721_user_last_login/migration.sql
  apps/server/src/prisma/schema/user.prisma
  apps/server/src/resources/project-service/business.ts
  apps/server/src/resources/project-service/queries.ts
  apps/server/src/resources/user/business.ts
  packages/hooks/package.json
  packages/hooks/src/hooks/hook.ts
  packages/shared/package.json
  packages/shared/src/schemas/config.ts
  packages/shared/src/schemas/user.ts
  plugins/nexus/package.json
  plugins/nexus/src/infos.ts
  plugins/nexus/src/maven.ts
  plugins/nexus/src/project.ts
  plugins/nexus/src/utils.ts
Labels: preview, built

#1451 refactor: :children_crossing: see env localization in admin project
  apps/client/src/views/admin/AdminProject.vue
Labels: built

#1453 Refactor/keycloak-internal
  plugins/keycloak/src/client.ts
  plugins/keycloak/src/config.ts
  plugins/keycloak/src/functions.ts
Labels: preview, built

#1452 Develop
  apps/client/src/views/admin/AdminProject.vue
  plugins/argocd/package.json
  plugins/argocd/src/functions.ts
  plugins/gitlab/package.json
  plugins/gitlab/src/class.ts
  plugins/keycloak/src/client.ts
  plugins/keycloak/src/config.ts
  plugins/keycloak/src/functions.ts
Labels: preview, built

#1408 feat: :sparkles: build project kv with config for projects
  apps/client/public/img/vault.svg
  plugins/argocd/package.json
  plugins/argocd/src/functions.ts
  plugins/kubernetes/package.json
  plugins/kubernetes/src/api.ts
  plugins/kubernetes/src/class.ts
  plugins/vault/README.md
  plugins/vault/package.json
  plugins/vault/src/class.ts
  plugins/vault/src/config.ts
  plugins/vault/src/env.d.ts
  plugins/vault/src/functions.ts
  plugins/vault/src/index.ts
  plugins/vault/src/infos.ts
  plugins/vault/src/monitor.ts
  plugins/vault/src/utils.ts
  plugins/vault/src/vso.ts
  pnpm-lock.yaml
Labels: enhancement, preview, built

#1462 refactor: :sparkles: option to disable Nexus
  plugins/nexus/src/infos.ts
  plugins/nexus/src/project.ts
Labels: built

#1461 fix: :bug: fix weird front behviours
  apps/client/cypress/e2e/specs/02-profile.e2e.ts
  apps/client/cypress/e2e/specs/admin/organizations.e2e.ts
  apps/client/cypress/e2e/specs/not-found.e2e.ts
  apps/client/src/components/OperationPanel.vue
  apps/client/src/components/ProjectLogsViewer.vue
  apps/client/src/components/ReplayButton.vue
  apps/client/src/router/index.ts
  apps/client/src/stores/project.ts
  apps/client/src/utils/project-utils.ts
  apps/client/src/views/admin/AdminProject.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoProjectWrapper.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/client/src/views/projects/DsoTeam.vue
  apps/client/src/views/projects/ManageEnvironments.vue
  apps/server/src/resources/project-member/business.ts
Labels: preview, built

#1464 Fix/bad migration
  apps/client/cypress/e2e/specs/admin/organizations.e2e.ts
  apps/server/src/prisma/migrations/20241104232541_add_pat/migration.sql
Labels: built

#1470 ci: :construction_worker: improve build pipeline
  .github/workflows/build.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: CI/CD, built

#1471 refactor: :recycle: support disabling vault-secrets
  apps/client/src/components/DsoSnackbar.vue
  packages/hooks/src/hooks/hook.spec.ts
  packages/hooks/src/utils/utils.ts
  plugins/vault/README.md
  plugins/vault/src/config.ts
  plugins/vault/src/functions.ts
Labels: built

#1456 feat: :art: use upsert zone hook to manage infra repo
  plugins/argocd/package.json
  plugins/argocd/src/functions.ts
  plugins/argocd/src/index.ts
  plugins/gitlab/package.json
  plugins/gitlab/src/class.ts
  plugins/gitlab/src/env.d.ts
  plugins/gitlab/src/functions.ts
  plugins/gitlab/src/index.ts
  plugins/gitlab/src/repositories.ts
Labels: built

#1473 Fix/vault kv v2
  plugins/vault/package.json
  plugins/vault/src/class.ts
  plugins/vault/src/utils.ts
Labels: built

#1457 feat: :sparkles: enable pwa on frontend
  apps/client/package.json
  apps/client/src/App.vue
  apps/client/src/components/ReloadPrompt.vue
  apps/client/src/env.d.ts
  apps/client/src/main.ts
  apps/client/tsconfig.json
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: preview, built

#1476 fix: :ambulance: broken admin token
  apps/client/cypress/e2e/specs/admin/tokens.e2e.ts
  apps/server/src/resources/user/business.ts
Labels: built

#1480 feat: :construction: zone kv store management
  plugins/argocd/src/functions.ts
  plugins/keycloak/package.json
  plugins/keycloak/src/env.d.ts
  plugins/keycloak/src/functions.ts
  plugins/vault/src/class.ts
  plugins/vault/src/functions.ts
  plugins/vault/src/index.ts
  pnpm-lock.yaml
Labels: built

#1483 refactor: :lipstick: improve layout
  apps/client/src/App.vue
  apps/client/src/components/ChoiceSelector.vue
  apps/client/src/components/DsoSnackbar.vue
  apps/client/src/components/ServicesConfig.vue
  apps/client/src/utils/project-utils.ts
  apps/client/src/views/admin/ListUser.vue
  apps/client/vite.config.ts
Labels: preview, built

#1484 ci: :construction_worker: improve ci workflow
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI/CD, built
