Repository cloud-pi-native/console, pull requests merged in 2024-12, with the labels that each got.

#1486 fix: :bug: retry delete project is failed
  apps/server/src/resources/project/business.spec.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/utils/hook-wrapper.ts
  plugins/kubernetes/src/namespace.ts
  plugins/sonarqube/src/functions.ts
Labels: built

#1487 fix: :bug: fix not displaying swagger
  apps/client/cypress/e2e/specs/redirection.e2e.ts
  apps/client/src/router/index.ts
Labels: built

#1488 Revert "refactor: :lipstick: improve layout"
  apps/client/src/App.vue
  apps/client/src/views/admin/ListUser.vue
Labels: preview, built

#1489 build: :arrow_up: upgrade dependencies
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .prototools
  apps/client/.eslintrc-auto-import.json
  apps/client/Dockerfile
  apps/client/cypress.config.ts
  apps/client/cypress/e2e/specs/home.e2e.ts
  apps/client/cypress/e2e/specs/redirection.e2e.ts
  apps/client/nginx/default.docker.conf
  apps/client/package.json
  apps/client/src/App.vue
  apps/client/src/components/EnvironmentForm.vue
  apps/client/src/router/index.ts
  apps/client/src/stores/project.ts
  apps/client/src/stores/user.ts
  apps/client/src/utils/keycloak/keycloak.ts
  apps/client/src/views/Swagger.vue
  apps/client/src/views/admin/AdminTokens.vue
  apps/client/src/views/admin/ListOrganizations.vue
  apps/client/src/views/profile/PersonalAccessTokens.vue
  apps/client/vite.config.ts
  apps/server/Dockerfile
  apps/server/package.json
  apps/server/src/prisma/migrations/20241216131342_dso/migration.sql
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/project-service/business.ts
  apps/server/src/utils/fastify.ts
  ci/act/workflows/ci.yml
  ci/scripts/cleanup.sh
  ci/scripts/setup.sh
  keycloak/realms/realm-dev.json
  misc/business-rules.md
  package.json
  packages/eslintconfig/package.json
  packages/eslintconfig/src/index.js
  packages/hooks/package.json
  packages/shared/package.json
  packages/shared/src/utils/const.ts
  packages/shared/src/utils/permissions.ts
  packages/test-utils/package.json
  patches/fastify-keycloak-adapter@2.3.2.patch
  plugins/argocd/package.json
  plugins/gitlab/package.json
  plugins/gitlab/src/user.ts
  plugins/harbor/package.json
  plugins/harbor/src/monitor.ts
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
  plugins/vault/package.json
  pnpm-lock.yaml
Labels: tech, preview, built

#1492 feat: :sparkles: store cluster secret in Vault
  apps/server/src/resources/cluster/queries.ts
  apps/server/src/utils/hook-wrapper.ts
  packages/hooks/src/hooks/index.ts
  plugins/argocd/src/cluster.ts
  plugins/argocd/src/functions.ts
  plugins/argocd/src/index.ts
  plugins/argocd/src/zone.ts
  plugins/gitlab/src/index.ts
  plugins/vault/src/class.ts
  plugins/vault/src/functions.ts
  plugins/vault/src/index.ts
Labels: built
