Repository cloud-pi-native/console, pull requests merged in 2024-01, with the labels that each got.

#901 ci: :green_heart: fix npm publish workflow
  .github/workflows/npm.yml
Labels: CI/CD

#903 build: :arrow_up: upgrade dependencies for release
  apps/client/.stylelintrc.cjs
  apps/client/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  package.json
  packages/shared/package.json
  packages/test-utils/package.json
  pnpm-lock.yaml
Labels: tech

#914 refactor: :art: fix typescript errors in client
  apps/client/package.json
  apps/client/src/App.vue
  apps/client/src/components/CIForm.vue
  apps/client/src/components/ClusterForm.vue
  apps/client/src/components/EnvironmentForm.vue
  apps/client/src/components/PermissionForm.vue
  apps/client/src/components/RepoForm.vue
  apps/client/src/icons.ts
  apps/client/src/router/index.ts
  apps/client/src/stores/admin/project.ts
  apps/client/src/stores/project-permission.ts
  apps/client/src/stores/project-repository.ts
  apps/client/src/stores/project-user.ts
  apps/client/src/utils/keycloak/keycloak.ts
  apps/client/src/utils/regex.spec.ts
  apps/client/src/utils/regex.ts
  apps/client/src/views/CreateProject.vue
  apps/client/src/views/NotFound.vue
  apps/client/src/views/projects/DsoProjects.vue
  pnpm-lock.yaml
Labels: dette technique

#919 chore: :arrow_up: upgrade node to LTS
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  apps/client/Dockerfile
  apps/client/src/components/RepoForm.ct.ts
  apps/server/Dockerfile
  ci/act/workflows/ci.yml
  package.json
Labels: dette technique
