Repository cloud-pi-native/console, pull requests merged in 2024-09, with the labels that each got.

#1349 refactor: :children_crossing: encourage cloned repository
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/client/cypress/e2e/specs/repos.e2e.ts
  apps/client/cypress/e2e/support/commands.ts
  apps/client/package.json
  apps/client/src/components/RepoForm.vue
  packages/shared/src/schemas/repository.ts
  packages/shared/src/utils/const.ts
  packages/shared/src/utils/schemas.spec.ts
  pnpm-lock.yaml
Labels: preview, built

#1343 Refactor/improve-repo-business
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/repository/router.ts
Labels: built

#1354 Develop
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/repository/router.ts
Labels: built

#1357 fix: :lipstick: better repo ui
  apps/client/src/components/RepoForm.vue
Labels: built

#1358 Develop
  apps/client/src/components/RepoForm.vue
Labels: built

#1363 ci: :construction_worker: fix cypress artifacts upload
  .github/workflows/scan.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
Labels: CI/CD, built

#1364 refactor: :recycle: should prevent auto cleanup
  plugins/gitlab/package.json
  plugins/gitlab/src/class.ts
  plugins/gitlab/src/repositories.ts
Labels: built

#1362 chore: :arrow_up: major upgrade vue-dsfr
  apps/client/.eslintrc-auto-import.json
  apps/client/cypress/components/support/commands.ts
  apps/client/cypress/e2e/specs/admin/organizations.e2e.ts
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/specs/admin/quotas.e2e.ts
  apps/client/cypress/e2e/specs/admin/roles.e2e.ts
  apps/client/cypress/e2e/specs/admin/stages.e2e.ts
  apps/client/cypress/e2e/specs/admin/zones.e2e.ts
  apps/client/cypress/e2e/specs/create-project.e2e.ts
  apps/client/cypress/e2e/specs/dashboard.e2e.ts
  apps/client/cypress/e2e/specs/environments.e2e.ts
  apps/client/cypress/e2e/specs/repos.e2e.ts
  apps/client/cypress/e2e/specs/roles.e2e.ts
  apps/client/cypress/e2e/specs/team.e2e.ts
  apps/client/cypress/e2e/support/commands.ts
  apps/client/package.json
  apps/client/src/App.vue
  apps/client/src/components/AdminRoleForm.vue
  apps/client/src/components/ChoiceSelector.vue
  apps/client/src/components/ClusterForm.vue
  apps/client/src/components/EnvironmentForm.vue
  apps/client/src/components/LoadingCt.vue
  apps/client/src/components/PaginationCt.vue
  apps/client/src/components/ProjectRoleForm.vue
  apps/client/src/components/QuotaForm.vue
  apps/client/src/components/RepoForm.vue
  apps/client/src/components/ServicesConfig.vue
  apps/client/src/components/SideMenu.vue
  apps/client/src/components/StageForm.vue
  apps/client/src/components/TeamCt.vue
  apps/client/src/components/ZoneForm.vue
  apps/client/src/icons.ts
  apps/client/src/main.ts
  apps/client/src/views/CreateProject.vue
  apps/client/src/views/DsoHome.vue
  apps/client/src/views/DsoMaintenance.vue
  apps/client/src/views/ServicesHealth.vue
  apps/client/src/views/admin/AdminRoles.vue
  apps/client/src/views/admin/ListClusters.vue
  apps/client/src/views/admin/ListLogs.vue
  apps/client/src/views/admin/ListOrganizations.vue
  apps/client/src/views/admin/ListPlugins.vue
  apps/client/src/views/admin/ListProjects.vue
  apps/client/src/views/admin/ListQuotas.vue
  apps/client/src/views/admin/ListStages.vue
  apps/client/src/views/admin/ListZones.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRepos.vue
  apps/client/src/views/projects/DsoRoles.vue
  apps/client/src/views/projects/ManageEnvironments.vue
  apps/client/vite.config.ts
  packages/shared/src/utils/const.ts
  pnpm-lock.yaml
Labels: built

#1369 feat: :sparkles: add admins api tokens
  apps/client/cypress/components/specs/admin-token-form.ct.ts
  apps/client/cypress/e2e/specs/admin/tokens.e2e.ts
  apps/client/src/components/AdminTokenForm.vue
  apps/client/src/components/SideMenu.vue
  apps/client/src/router/index.ts
  apps/client/src/stores/admin-token.spec.ts
  apps/client/src/stores/admin-token.ts
  apps/client/src/views/admin/AdminTokens.vue
  apps/server/package.json
  apps/server/src/prisma/migrations/20240916141253_token/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/admin-role/router.ts
  apps/server/src/resources/admin-token/business.spec.ts
  apps/server/src/resources/admin-token/business.ts
  apps/server/src/resources/admin-token/router.spec.ts
  apps/server/src/resources/admin-token/router.ts
  apps/server/src/resources/cluster/router.ts
  apps/server/src/resources/environment/router.ts
  apps/server/src/resources/index.ts
  apps/server/src/resources/log/business.spec.ts
  apps/server/src/resources/log/router.ts
  apps/server/src/resources/organization/router.ts
  apps/server/src/resources/project-member/router.ts
  apps/server/src/resources/project-role/router.ts
  apps/server/src/resources/project-service/router.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/project/router.ts
  apps/server/src/resources/quota/router.ts
  apps/server/src/resources/repository/router.ts
  apps/server/src/resources/stage/router.ts
  apps/server/src/resources/system/config/router.ts
  apps/server/src/resources/system/settings/router.ts
  apps/server/src/resources/user/business.spec.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/router.spec.ts
  apps/server/src/resources/user/router.ts
  apps/server/src/resources/zone/router.ts
  apps/server/src/types/index.ts
  apps/server/src/utils/const.ts
  apps/server/src/utils/controller.ts
  apps/server/src/utils/errors.ts
  apps/server/src/utils/keycloak-utils.spec.ts
  apps/server/src/utils/keycloak-utils.ts
  apps/server/src/utils/keycloak.ts
  package.json
  packages/shared/src/api-client.ts
  packages/shared/src/contracts/admin-token.ts
  packages/shared/src/contracts/index.ts
  packages/shared/src/schemas/index.ts
  packages/shared/src/schemas/token.ts
  packages/shared/src/schemas/utils.ts
  packages/shared/src/utils/functions.ts
  packages/shared/src/utils/permissions.ts
  packages/test-utils/src/imports/data.ts
  patches/fastify-keycloak-adapter@2.2.0.patch
  pnpm-lock.yaml
Labels: preview, built

#1373 ci: :construction_worker: add comment tag on preview comment
  .github/workflows/preview.yml
Labels: CI/CD, built

#1370 feat: :sparkles: add users search filter (admin)
  apps/client/src/components/AdminRoleForm.vue
  apps/client/src/stores/users.ts
  apps/client/src/views/admin/AdminRoles.vue
  apps/server/src/resources/user/business.spec.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/router.ts
  packages/shared/src/contracts/user.ts
  packages/shared/src/schemas/role.ts
  packages/shared/src/schemas/user.ts
  packages/shared/src/schemas/utils.ts
Labels: preview, built

#1374 chore: :arrow_up: upgrade node and pnpm
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .prototools
  apps/client/Dockerfile
  apps/server/Dockerfile
  package.json
Labels: built

#1378 fix: :bug: fix behaviour of complex querying on user list
  apps/client/src/stores/project-member.ts
  apps/client/src/views/admin/ListUser.vue
  apps/server/src/resources/user/business.spec.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/router.ts
Labels: built

#1379 build: :construction_worker: auto trigger chart update
  .github/workflows/cd.yml
Labels: built

#1383 fix: :passport_control: allow more actions to admin token
  apps/server/src/init/db/utils.ts
  apps/server/src/prisma/migrations/20240919122331_optional_user_id/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/admin-token/router.ts
  apps/server/src/resources/cluster/business.ts
  apps/server/src/resources/cluster/router.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/environment/router.ts
  apps/server/src/resources/log/queries.ts
  apps/server/src/resources/organization/business.ts
  apps/server/src/resources/project-member/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/router.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/utils/controller.ts
  packages/shared/package.json
  packages/shared/src/contracts/cluster.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/schemas/cluster.ts
Labels: built

#1384 Develop
  apps/server/src/init/db/utils.ts
  apps/server/src/prisma/migrations/20240919122331_optional_user_id/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/admin-token/router.ts
  apps/server/src/resources/cluster/business.ts
  apps/server/src/resources/cluster/router.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/environment/router.ts
  apps/server/src/resources/log/queries.ts
  apps/server/src/resources/organization/business.ts
  apps/server/src/resources/project-member/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/router.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/utils/controller.ts
  packages/shared/package.json
  packages/shared/src/contracts/cluster.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/schemas/cluster.ts
Labels: built

#1386 feat: :loud_sound: add logger object
  apps/client/package.json
  apps/server/package.json
  apps/server/src/app.ts
  apps/server/src/connect.spec.ts
  apps/server/src/connect.ts
  apps/server/src/init/db/index.ts
  apps/server/src/prepare-app.spec.ts
  apps/server/src/prepare-app.ts
  apps/server/src/prisma/migrations/20240923142722_dso/migration.sql
  apps/server/src/prisma/migrations/migration_lock.toml
  apps/server/src/prisma/schema.prisma
  apps/server/src/server.spec.ts
  apps/server/src/server.ts
  apps/server/src/utils/fastify.ts
  apps/server/src/utils/logger.ts
  ci/act/docker/registry/docker-compose.registry.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.integ.yml
  docker/docker-compose.local.yml
  docker/docker-compose.prod.yml
  packages/eslintconfig/package.json
  packages/eslintconfig/src/index.js
  pnpm-lock.yaml
Labels: enhancement, built

#1390 ci: :construction_worker: fix trivy pull rate limits
  .github/workflows/scan.yml
Labels: CI/CD, built

#1389 fix: :bug: change imports exports to not use z.lazy, fix swagger-ui
  apps/client/src/components/DsoBadge.vue
  apps/client/src/components/ProjectRoleForm.vue
  apps/client/src/stores/project-services.ts
  apps/client/src/stores/project.ts
  apps/client/src/views/admin/ListLogs.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/server/src/resources/cluster/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/utils/const.ts
  apps/server/src/utils/controller.ts
  apps/server/src/utils/keycloak-utils.ts
  packages/shared/package.json
  packages/shared/src/contracts/_utils.ts
  packages/shared/src/contracts/admin-role.ts
  packages/shared/src/contracts/admin-token.ts
  packages/shared/src/contracts/cluster.ts
  packages/shared/src/contracts/environment.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/contracts/organization.ts
  packages/shared/src/contracts/project-member.ts
  packages/shared/src/contracts/project-role.ts
  packages/shared/src/contracts/project-service.ts
  packages/shared/src/contracts/project.ts
  packages/shared/src/contracts/quota.ts
  packages/shared/src/contracts/repository.ts
  packages/shared/src/contracts/service-monitor.ts
  packages/shared/src/contracts/stage.ts
  packages/shared/src/contracts/system.ts
  packages/shared/src/contracts/user.ts
  packages/shared/src/contracts/zone.ts
  packages/shared/src/index.ts
  packages/shared/src/schemas/_utils.ts
  packages/shared/src/schemas/cluster.ts
  packages/shared/src/schemas/environment.ts
  packages/shared/src/schemas/organization.ts
  packages/shared/src/schemas/project.ts
  packages/shared/src/schemas/quota.ts
  packages/shared/src/schemas/repository.ts
  packages/shared/src/schemas/role.ts
  packages/shared/src/schemas/services.ts
  packages/shared/src/schemas/stage.ts
  packages/shared/src/schemas/system.ts
  packages/shared/src/schemas/token.ts
  packages/shared/src/schemas/user.ts
  packages/shared/src/schemas/zone.ts
  packages/shared/src/utils/const.ts
  packages/shared/src/utils/permissions.ts
  packages/shared/src/utils/schemas.ts
Labels: built

#1392 Refactor/ts-rest-use-pathPrefix
  .github/workflows/scan.yml
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/specs/home.e2e.ts
  apps/client/src/App.vue
  apps/server/src/app.spec.ts
  apps/server/src/resources/system/router.spec.ts
  apps/server/src/utils/fastify.ts
  packages/shared/package.json
  packages/shared/src/api-client.ts
  packages/shared/src/contracts/admin-role.ts
  packages/shared/src/contracts/admin-token.ts
  packages/shared/src/contracts/cluster.ts
  packages/shared/src/contracts/environment.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/contracts/organization.ts
  packages/shared/src/contracts/project-member.ts
  packages/shared/src/contracts/project-role.ts
  packages/shared/src/contracts/project-service.ts
  packages/shared/src/contracts/project.ts
  packages/shared/src/contracts/quota.ts
  packages/shared/src/contracts/repository.ts
  packages/shared/src/contracts/service-monitor.ts
  packages/shared/src/contracts/stage.ts
  packages/shared/src/contracts/system.ts
  packages/shared/src/contracts/zone.ts
  packages/shared/src/utils/const.ts
Labels: preview, built

#1393 Fix/home-tabs
  apps/client/src/views/DsoHome.vue
Labels: built

#1396 fix: :loud_sound: change log logic in sonarqube plugin
  .github/workflows/ci.yml
  plugins/sonarqube/package.json
  plugins/sonarqube/src/functions.ts
  plugins/sonarqube/src/index.ts
Labels: built

#1387 feat: :sparkles: keycloak client management for configuring sso oidc of each argocd zone
  apps/client/cypress.config.ts
  apps/client/cypress/components/specs/zone-form.ct.ts
  apps/client/cypress/e2e/specs/admin/zones.e2e.ts
  apps/client/src/components/ZoneForm.vue
  apps/client/src/views/admin/ListZones.vue
  apps/server/src/__mocks__/utils/hook-wrapper.ts
  apps/server/src/prisma/migrations/20240923155416_dso/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/cluster/queries.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/zone/business.spec.ts
  apps/server/src/resources/zone/business.ts
  apps/server/src/resources/zone/queries.ts
  apps/server/src/resources/zone/router.spec.ts
  apps/server/src/resources/zone/router.ts
  apps/server/src/utils/hook-wrapper.ts
  packages/hooks/package.json
  packages/hooks/src/hooks/hook-zone.ts
  packages/hooks/src/hooks/index.ts
  packages/shared/package.json
  packages/shared/src/schemas/zone.ts
  packages/test-utils/src/imports/data.ts
  packages/test-utils/src/utils/random-utils.ts
  plugins/keycloak/package.json
  plugins/keycloak/src/functions.ts
  plugins/keycloak/src/index.ts
Labels: built
