Repository cloud-pi-native/console, pull requests merged in 2024-06, with the labels that each got.

#1159 feat: :sparkles: add text filter for admin user list
  apps/client/cypress/e2e/specs/admin/users.e2e.ts
  apps/client/src/views/admin/ListProjects.vue
  apps/client/src/views/admin/ListUser.vue
Labels: enhancement

#1169 fix: :bug: handle vault ha for status monitor
  plugins/vault/package.json
  plugins/vault/src/monitor.ts
Labels: bug

#1168 refactor: :label: improve project and environment contracts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/environment/router.ts
  apps/server/src/resources/log/admin/router.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/quota/admin/business.ts
  apps/server/src/resources/quota/admin/controllers.spec.ts
  apps/server/src/resources/quota/queries.ts
  apps/server/src/resources/stage/admin/business.ts
  apps/server/src/resources/stage/admin/controllers.spec.ts
  apps/server/src/resources/stage/business.ts
  apps/server/src/resources/stage/queries.ts
  packages/shared/src/contracts/environment.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/schemas/environment.ts
  packages/shared/src/schemas/quota.ts
  packages/shared/src/schemas/stage.ts
  packages/shared/src/utils/const.ts
Labels: tech

#1188 feat: :sparkles: prevent env and repo deletion if project is locked
  apps/client/cypress/e2e/specs/environments.e2e.ts
  apps/client/cypress/e2e/specs/repos.e2e.ts
  apps/client/src/components/EnvironmentForm.vue
  apps/client/src/components/RepoForm.vue
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/environment/controllers.spec.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/repository/controllers.spec.ts
Labels: enhancement
