Repository cloud-pi-native/console, pull requests merged in 2024-02, with the labels that each got.

#951 refactor: :recycle: enforce typescript:S6544 rule
  apps/server/src/plugins.ts
  pnpm-lock.yaml
Labels: dette technique

#958 fix: :label: add missing fastify keycloak adapter patch to improve types
  package.json
  patches/fastify-keycloak-adapter@2.1.10.patch
  pnpm-lock.yaml
Labels: tech

#957 refactor: :label: add plugins types to enforce strict mode
  plugins/argo/src/app-project.ts
  plugins/argo/tsconfig.json
  plugins/harbor/src/permission.ts
  plugins/harbor/src/robot.ts
  plugins/harbor/src/utils.ts
  plugins/harbor/tsconfig.json
  plugins/keycloak/src/group.ts
  plugins/keycloak/tsconfig.json
  plugins/sonarqube/src/group.ts
  plugins/sonarqube/src/project.ts
  plugins/sonarqube/src/user.ts
  plugins/sonarqube/tsconfig.json
  plugins/vault/src/class.ts
  plugins/vault/src/functions.ts
  plugins/vault/tsconfig.json
Labels: tech

#961 refactor: :label: add types on shared package
  packages/shared/package.json
  packages/shared/src/utils/date.ts
  packages/shared/src/utils/functions.ts
  packages/shared/src/utils/schemas.ts
  packages/shared/tsconfig.json
Labels: tech

#963 chore: :construction_worker: enable multi arch build on new release
  .github/workflows/cd.yml
Labels: tech

#967 ci: :construction_worker: upgrade cicd actions versions
  .github/workflows/build.yml
  .github/workflows/cache.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-deploy.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .release-please-manifest.json
  ci/act/workflows/build.yml
  ci/act/workflows/cache.yml
  ci/act/workflows/ci.yml
  ci/act/workflows/lint.yml
  ci/act/workflows/release.yml
  ci/act/workflows/scan.yml
  ci/act/workflows/tests-component.yml
  ci/act/workflows/tests-deploy.yml
  ci/act/workflows/tests-e2e.yml
  ci/act/workflows/tests-unit.yml
  release-please-config.json
Labels: CI/CD

#972 ci: :green_heart: fix artifacts conflicts upload
  .github/workflows/scan.yml
  ci/act/workflows/scan.yml
Labels: CI/CD
