Repository cloud-pi-native/console, pull requests merged in 2024-04, with the labels that each got.

#1035 ci: :green_heart: upgrade cypress to fix firefox broken tests
  apps/client/package.json
  pnpm-lock.yaml
Labels: bug, CI/CD

#1052 fix: :bug: app version in client footer
  apps/client/vite.config.ts
Labels: bug

#1050 ci: :construction_worker: restore all files on unit tests cache hit
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
Labels: CI/CD

#1060 fix: :bug: handle stage and zone changes in environment form
  apps/client/cypress/e2e/specs/environments.e2e.ts
  apps/client/src/components/EnvironmentForm.vue
Labels: bug

#1061 fix: :bug: get only client app version from env on production build
  apps/client/vite.config.ts
Labels: bug

#1064 docs: :memo: update readme
  README.md
Labels: documentation

#1074 chore: upgrade nodejs to v20.12.2
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  apps/client/Dockerfile
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/server/Dockerfile
  package.json
Labels: tech

#1076 docs: :memo: add release section in readme
  README.md
Labels: documentation

#1079 chore: :memo: add definition of done in issue templates
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
Labels: documentation

#1077 build: :arrow_up: upgrade js dependencies
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  README.md
  apps/client/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  ci/scripts/run-tests.sh
  package.json
  packages/eslintconfig/package.json
  packages/hooks/package.json
  packages/shared/package.json
  packages/shared/src/utils/schemas.spec.ts
  packages/test-utils/package.json
  plugins/argocd/package.json
  plugins/gitlab/package.json
  plugins/harbor/package.json
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
  plugins/vault/package.json
  pnpm-lock.yaml
Labels: tech

#1090 refactor: :recycle: handle disabling helm postgres deployment
  helm/templates/cm-postgres.yaml
  helm/templates/cm-scripts.yaml
  helm/templates/cm-server.yaml
  helm/templates/deployment-postgres.yaml
  helm/templates/services-postgres.yaml
  helm/templates/services.yaml
  helm/values.yaml
Labels: CI/CD
