Repository cloud-pi-native/console, pull requests merged in 2024-05, with the labels that each got.

#1127 refactor: :fire: remove unused files
  apps/server/src/__mocks__/app.ts
  ci/scripts/init-project.sh
  helm/templates/services-postgres.yaml
Labels: refactor

#1128 refactor: :recycle: improve integration env vars management
  .gitignore
  README.md
  apps/server/.env.integ-example
  ci/kind/env/dso-values-dev.yaml
  ci/kind/env/dso-values-integ-example.yaml
  ci/kind/env/dso-values.yaml
  ci/kind/env/kind-values.example.yml
  ci/kind/run-create.sh
  ci/kind/run.sh
  docker/docker-compose.dev.yml
  docker/docker-compose.integ.yml
  docker/docker-compose.prod.yml
  env/.env.integ-example
  package.json
Labels: refactor

#1131 Docs/add screenshot in readme
  README.md
  ci/kind/env/dso-values.yaml
  misc/images/environments.png
  misc/images/members.png
  misc/images/projects.png
  misc/images/repositories.png
  misc/images/services.png
  misc/images/status.png
Labels: documentation

#1132 chore: :bug: add missing env for docker integ build
  package.json
Labels: tech

#1137 fix: :bug: update cluster logic
  apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
  apps/server/src/resources/cluster/admin/business.ts
  apps/server/src/resources/cluster/admin/controllers.spec.ts
  apps/server/src/resources/cluster/queries.ts
Labels: bug
