Repository cloud-pi-native/console, pull requests merged in 2024-03, with the labels that each got.

#975 fix: :technologist: fix docker volumes for integ mode
  .github/workflows/ci.yml
  docker/docker-compose.integ.yml
  plugins/keycloak/src/group.ts
Labels: docker, tech

#977 refactor: :rotating_light: fix ts errors in server
  apps/server/src/__mocks__/app.ts
  apps/server/src/app.ts
  apps/server/src/resources/cluster/admin/business.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/environment/controllers.spec.ts
  apps/server/src/resources/environment/controllers.ts
  apps/server/src/resources/log/admin/queries.ts
  apps/server/src/resources/organization/admin/business.ts
  apps/server/src/resources/organization/controllers.ts
  apps/server/src/resources/permission/business.ts
  apps/server/src/resources/permission/queries.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/controllers.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/quota/admin/business.ts
  apps/server/src/resources/quota/admin/controllers.ts
  apps/server/src/resources/stage/admin/business.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/controllers.spec.ts
  apps/server/src/utils/controller.ts
  packages/hooks/src/hooks/project.ts
  packages/shared/src/resources/environment/openApiSchema.ts
  packages/shared/src/resources/permission/openApiSchema.ts
  packages/shared/src/resources/project/openApiSchema.ts
  packages/shared/src/resources/quota/openApiSchema.ts
  packages/shared/src/resources/stage/openApiSchema.ts
  packages/shared/src/resources/user/openApiSchema.ts
Labels: dette technique

#979 Fix/send cluster in hook payload
  apps/server/src/resources/environment/queries.ts
  apps/server/src/resources/permission/business.ts
Labels: bug

#978 chore: :technologist: fix files binding in docker-compose dev
  .vscode/launch.json
  README.md
  apps/client/package.json
  apps/client/tsconfig.json
  apps/server/Dockerfile
  apps/server/package.json
  docker/docker-compose.dev.yml
  docker/docker-compose.integ.yml
  package.json
  packages/hooks/package.json
  packages/shared/package.json
  packages/test-utils/package.json
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.base.json
  plugins/argocd/package.json
  plugins/gitlab/package.json
  plugins/gitlab/tsconfig.json
  plugins/harbor/package.json
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
  plugins/vault/package.json
  turbo.json
Labels: tech

#983 Fix/update compile command
  README.md
  apps/server/Dockerfile
  packages/hooks/package.json
  packages/shared/package.json
  plugins/argocd/package.json
  plugins/gitlab/package.json
  plugins/harbor/package.json
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
  plugins/vault/package.json
Labels: bug

#995 fix: :green_heart: fix ci-cd build and release
  .github/workflows/build.yml
  release-please-config.json
Labels: bug, CI/CD

#997 fix: :bug: correctly handle external plugins init
  apps/server/src/plugins.ts
Labels: bug

#999 ci: :green_heart: fallback to trigger branch name on manual build
  .github/workflows/build.yml
Labels: CI/CD

#1007 ci: :green_heart: fix release packages version auto bump
  .github/workflows/release.yml
Labels: CI/CD

#1016 chore: :rotating_light: remove unecessary ts-ignores and add some
  apps/client/src/stores/admin/log.spec.ts
  apps/server/src/connect.spec.ts
  apps/server/src/resources/cluster/admin/business.ts
  apps/server/src/resources/cluster/admin/controllers.spec.ts
  apps/server/src/resources/cluster/admin/router.ts
  apps/server/src/resources/cluster/business.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/log/admin/queries.ts
  apps/server/src/resources/organization/admin/business.ts
  apps/server/src/resources/organization/business.ts
  apps/server/src/resources/organization/queries.ts
  apps/server/src/resources/organization/router.ts
  apps/server/src/resources/permission/business.ts
  apps/server/src/resources/permission/queries.ts
  apps/server/src/resources/project/admin/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/quota/queries.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/stage/admin/business.ts
  apps/server/src/resources/stage/business.ts
  apps/server/src/resources/stage/queries.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/resources/user/queries.ts
  apps/server/src/resources/user/role-queries.ts
  apps/server/src/resources/utils/business.ts
  apps/server/src/utils/controller.ts
  apps/server/src/utils/hook-wrapper.ts
  apps/server/src/utils/mocks.ts
  misc/business-rules.md
  packages/shared/src/contracts/user.ts
  packages/shared/src/schemas/cluster.ts
Labels: dette technique

#1020 fix: :bug: reload user projects after hooks replay
  apps/client/src/stores/admin/project.spec.ts
  apps/client/src/stores/admin/project.ts
  apps/client/src/stores/project.spec.ts
  apps/client/src/stores/project.ts
  apps/client/src/views/admin/ListProjects.vue
Labels: bug
