Repository cloud-pi-native/console, pull requests merged in 2024-10, with the labels that each got.

#1399 feat: :sparkles: introduce warn status on project
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/specs/dashboard.e2e.ts
  apps/client/src/App.vue
  apps/client/src/components/AdminTokenForm.vue
  apps/client/src/components/ServicesConfig.vue
  apps/client/src/components/TeamCt.vue
  apps/client/src/main.css
  apps/client/src/stores/project.spec.ts
  apps/client/src/stores/project.ts
  apps/client/src/stores/services-monitor.ts
  apps/client/src/views/CreateProject.vue
  apps/client/src/views/admin/ListPlugins.vue
  apps/client/src/views/admin/ListProjects.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoTeam.vue
  apps/server/src/prisma/migrations/20240928002900_dso/migration.sql
  apps/server/src/prisma/schema.prisma
  apps/server/src/resources/project/queries.ts
  apps/server/src/utils/hook-wrapper.ts
  packages/shared/src/utils/const.ts
  packages/shared/src/utils/functions.ts
  packages/test-utils/src/imports/data.ts
  plugins/gitlab/package.json
  plugins/gitlab/src/functions.ts
  plugins/gitlab/src/index.ts
  plugins/gitlab/src/members.ts
  plugins/kubernetes/package.json
  plugins/kubernetes/src/class.ts
  plugins/kubernetes/src/namespace.ts
Labels: preview, built

#1400 feat: :sparkles: show short logs about project to users
  apps/client/cypress/e2e/specs/01-logs.e2e.ts
  apps/client/src/components/LogsViewer.vue
  apps/client/src/components/PaginationCt.vue
  apps/client/src/components/ProjectLogsViewer.vue
  apps/client/src/main.css
  apps/client/src/router/index.ts
  apps/client/src/stores/log.ts
  apps/client/src/views/admin/ListLogs.vue
  apps/client/src/views/admin/ListProjects.vue
  apps/client/src/views/projects/DsoDashboard.vue
  apps/client/src/views/projects/DsoProjectWrapper.vue
  apps/client/src/views/projects/DsoProjects.vue
  apps/client/src/views/projects/DsoRoles.vue
  apps/server/src/init/db/utils.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/log/business.spec.ts
  apps/server/src/resources/log/business.ts
  apps/server/src/resources/log/queries.ts
  apps/server/src/resources/log/router.spec.ts
  apps/server/src/resources/log/router.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/queries-index.ts
  apps/server/src/resources/repository/business.ts
  packages/shared/src/contracts/log.ts
  packages/shared/src/schemas/index.ts
  packages/shared/src/schemas/log.ts
  packages/test-utils/src/imports/data.ts
Labels: preview, built

#1403 fix: :ambulance: no check on api response
  packages/shared/src/contracts/environment.ts
  packages/shared/src/contracts/repository.ts
Labels: built

#1409 ci: :construction_worker: bypass trivy rate limit errors
  .github/workflows/scan.yml
Labels: CI/CD, built

#1414 ci: :technologist: re-deploy preview apps on new build
  .github/workflows/build.yml
Labels: CI/CD, built

#1416 chore: :green_heart: preview jobs needs to be executed after merge
  .github/workflows/build.yml
Labels: built

#1417 ci: :green_heart: fix app preview re-deploy
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI/CD, built

#1418 Chore/dead-code
  .github/workflows/build.yml
  apps/server/src/__mocks__/utils/hook-wrapper.ts
  apps/server/src/utils/hook-wrapper.ts
  apps/server/src/utils/mocks.ts
  packages/hooks/src/hooks/hook-user.ts
  plugins/keycloak/src/functions.ts
  plugins/keycloak/src/index.ts
Labels: preview, built

#1419 ci: :green_heart: really fix re-deploy preview app
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI/CD, built

#1421 feat: :lipstick: add argocd urls for each zone
  apps/server/src/resources/project-service/business.ts
  packages/hooks/src/services.ts
  plugins/argocd/package.json
  plugins/argocd/src/functions.ts
  plugins/argocd/src/infos.ts
Labels: built

#1422 Feat/user-plugins-message
  apps/client/src/components/LogsViewer.vue
  packages/hooks/src/hooks/hook.ts
  packages/shared/src/schemas/log.ts
  plugins/gitlab/package.json
  plugins/gitlab/src/functions.ts
  plugins/keycloak/package.json
  plugins/keycloak/src/functions.ts
  plugins/nexus/package.json
  plugins/nexus/src/project.ts
  plugins/sonarqube/package.json
  plugins/sonarqube/src/check.ts
  plugins/vault/package.json
  plugins/vault/src/functions.ts
Labels: preview, built

#1423 Refactor/nexus
  packages/hooks/package.json
  plugins/harbor/package.json
  plugins/harbor/src/functions.ts
  plugins/nexus/src/infos.ts
  plugins/nexus/src/project.ts
  plugins/nexus/tsconfig.json
Labels: built

#1424 Refactor/align-schemas
  apps/server/src/resources/environment/router.spec.ts
  apps/server/src/resources/project-service/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/project/queries.ts
  apps/server/src/resources/project/router.ts
  apps/server/src/resources/repository/router.spec.ts
  apps/server/src/resources/system/config/business.ts
  apps/server/src/utils/mocks.ts
  packages/shared/src/contracts/environment.ts
  packages/shared/src/contracts/project.ts
  packages/shared/src/contracts/repository.ts
  packages/shared/src/schemas/environment.ts
  packages/shared/src/schemas/repository.ts
  packages/shared/src/utils/schemas.spec.ts
Labels: built

#1426 feat: :lipstick: adding the project id in namespace labels
  plugins/argocd/src/functions.ts
Labels: built

#1428 Tech/node22
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .prototools
  apps/client/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  ci/act/workflows/ci.yml
  package.json
  packages/hooks/package.json
  packages/shared/package.json
  packages/test-utils/package.json
  plugins/argocd/package.json
  plugins/gitlab/package.json
  plugins/harbor/package.json
  plugins/keycloak/package.json
  plugins/kubernetes/package.json
  plugins/nexus/package.json
  plugins/sonarqube/package.json
  plugins/vault/package.json
  pnpm-lock.yaml
Labels: built

#1432 fix: :bug: update depracated import assertion type syntax
  apps/server/src/plugins.ts
Labels: bug, built

#1430 Develop
  apps/server/src/plugins.ts
Labels: preview, built
