Repository cloud-pi-native/console, pull requests merged in 2024-07, with the labels that each got.

#1215 ci: :bug: fix local e2e tests with docker
  package.json
Labels: docker, CI/CD

#1256 chore: :arrow_up: upgrade dsfr-gouv
  apps/client/cypress/components/specs/cluster-form.ct.ts
  apps/client/cypress/components/specs/quota-form.ct.ts
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/client/cypress/components/specs/stage-form.ct.ts
  apps/client/cypress/components/specs/zone-form.ct.ts
  apps/client/cypress/e2e/specs/admin/clusters.e2e.ts
  apps/client/cypress/e2e/specs/admin/projects.e2e.ts
  apps/client/cypress/e2e/specs/admin/quotas.e2e.ts
  apps/client/cypress/e2e/specs/admin/stages.e2e.ts
  apps/client/cypress/e2e/specs/admin/users.e2e.ts
  apps/client/cypress/e2e/specs/admin/zones.e2e.ts
  apps/client/cypress/e2e/specs/create-project.e2e.ts
  apps/client/cypress/e2e/specs/permissions.e2e.ts
  apps/client/cypress/e2e/specs/repos.e2e.ts
  apps/client/cypress/e2e/specs/team.e2e.ts
  apps/client/cypress/e2e/support/commands.ts
  apps/client/package.json
  apps/client/src/components/ClusterForm.vue
  apps/client/src/components/QuotaForm.vue
  apps/client/src/components/RepoForm.vue
  apps/client/src/components/SuggestionInput.vue
  pnpm-lock.yaml
Labels: technical debt

#1259 Chore/upgrade nodejs
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/npm.yml
  .github/workflows/tests-component.yml
  .github/workflows/tests-e2e.yml
  .github/workflows/tests-unit.yml
  .prototools
  apps/client/Dockerfile
  apps/client/cypress/components/specs/repo-form.ct.ts
  apps/client/package.json
  apps/server/Dockerfile
  package.json
  pnpm-lock.yaml
Labels: tech

#1262 fix: :art: harmonize hook calling in business
  apps/server/src/resources/cluster/admin/business.ts
  apps/server/src/resources/environment/business.ts
  apps/server/src/resources/organization/business.ts
  apps/server/src/resources/permission/business.ts
  apps/server/src/resources/project/business.ts
  apps/server/src/resources/repository/business.ts
  apps/server/src/resources/user/business.ts
  apps/server/src/utils/hook-wrapper.ts
Labels: bug

#1296 ci: :construction_worker: handle app preview
  .github/labeler/build.yml
  .github/workflows/ci.yml
  .github/workflows/label.yml
  .github/workflows/preview.yml
  ci/preview/applicationset.yaml
Labels: preview, built
